#!/bin/bash

rm -rf .stage \
  && mkdir .stage \
  && cd .stage \
  && git init \
  && git checkout -b gh-pages \
  && git remote add origin git@github.com:blakelapierre/dash-preact-cycle \
  && ((git pull origin gh-pages && git rm -r .) || echo "new gh-pages") \
  && echo "copying" \
  && cp  -r ../.dist/* . \
  && echo "medash.xyz" > CNAME \
  && git add . \
  && echo "committing && pushing" \
  && git commit -m "publish" \
  && git push origin gh-pages \
  && echo "checking out" \
  && git checkout typescript \
  && echo "publish done"